### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by coolpalani** [wako057/openstack-salt#1]
Hello,

Could you add little brief notes about your salt formula?
Is this formula for one node or multi node installations on virtual machine or physical server?
What about prerequisites ?

**Comment by wako057** [comment]
Hello Coolpalani,

These formula are developp for a multi-node installations for a setup of a openstack solution. That does not include the creation of the networks of the solutions
The master i use is a Debian 9 saltstack 2017.7
The minions are Ubuntu 16.04
The virtual machine should not be a blocking point, but it's tested on a three phsysical servers on ubuntu, 
I've implemented the tutorial, i'm currently adding the orchestration and the container sections that I need.
To be simple, in order to make it work the important informations have to filled in:

>  openstack-salt/pillar/global_vars.sls
> password: All the password required and centralized
> infra: an overview of the architecture, if you have more than 1 compute, there will be things to amend probably, I use it a few, but it was on the early stage of the development.
> nodes: The most important part, where you defined the behaviour of each node, the ip are the physical or management interface.

There is many things to improve, but here is how I use it.

```
salt '*' state.apply openstack.prerequis
salt '*' state.apply openstack.general
salt '*' state.apply openstack-openrc

```
=> I will make a commit tomorrow that will do the three call by  salt '*' state.apply openstack
then

```
salt '*' state.apply keystone
salt '*' state.apply glance
salt '*' state.apply nova
salt '*' state.apply neutron
salt '*' state.apply dashboard
salt '*' state.apply cinder
```

If ever i see that something is wrong, i
 
```
salt '*' state.apply openstack.stop-services
salt '*' state.apply database.recreatedb
```

and made the appropriate change.

network_level: l3 OR l2
=> in order to define if you need level 2 or level 3 network, you will probably need the l3.

The 
bootstrap-salt-elasticsearch.sh, bootstrap-salt-master-01.sh
are file that i use to build virtual machines on the cloud once the setup is done, i use salt to configure the server on the cloud created.

creation_reseaux.txt
=> Txt file where i fill the useful command i use once the cloud is setup


It's a work still in progress, if ever you have any special need or recommandation, feel free to contact me.

Regards.

**Comment by coolpalani** [comment]
Many of peoples are still facing to setup a fully working network OpenStack. If you are taking bit priority and release future commits, it would be useful to openstack folks.
Also in each commit if you are adding notes of your changes/updates, it will be helpful to your code followers. 
Thank you very much for your contributions.

**Comment by wako057** [comment]
Actually, the last openstack repository upgrade have induce a bug on the authentification
mechanism  with the previous instructions of the tutorial. It Also change
the way that I used to create Vms on the provider network, i've found the way to make It work and spawning a vm on the provider network, i have to use the neutron cli instead of the openstack cli.
It seems that it's impact only the vm spawn on the provider network, not the self-service's

=> no need to amend keystone-paste.ini
=> Some warning appear in the log, when I try to fix them the spawn doesnt work anymore



Gregory GERARD

**Comment by coolpalani** [comment]
Sounds good.
Then I will initiate to build an OpenStack via SaltStack.

**Comment by wako057** [comment]
Release fixed
Heat Working
I have given some more extra-information in the readme
